# ---------------------------------------------------------------------------- #
#                                     AMCL                                     #
# ---------------------------------------------------------------------------- #

# ---------------------------- Frame name settings --------------------------- #

global_frame_id: "map"
odom_frame_id: "odom"
base_frame_id: "base_link"
scan_topic: "scan"

# ------------------------------ Basic settings ------------------------------ #

use_map_topic: false
initial_pose_x: 0
initial_pose_y: 0
initial_pose_a: 0

# ------------------------------ Laser settings ------------------------------ #

laser_model_type: likelihood_field
laser_max_beams: 60
laser_max_range: 12.0

laser_z_hit: 1.0
laser_z_short: 0.05
laser_z_max: 0.05
laser_z_rand: 0.35
laser_sigma_hit: 0.05
laser_lambda_short: 0.1
laser_likelihood_max_dist: 4.0

# -------------------------- Odometry model settings ------------------------- #

# odom_model_type: diff-corrected
odom_model_type: omni-corrected

# Expected process noise in odometry's rotation estimate from rotation.
# odom_alpha1: 0.008
odom_alpha1: 0.01
# Expected process noise in odometry's rotation estimate from translation.
# odom_alpha2: 0.04
odom_alpha2: 0.01

# Expected process noise in odometry's translation estimate from translation.
# odom_alpha3: 0.004
odom_alpha3: 0.008

# Expected process noise in odometry's translation estimate from rotation.
# odom_alpha4: 0.025
odom_alpha4: 0.008

# For Omni models only: translation noise.
odom_alpha5: 0.01

# ------------------------ Particle Filter Parameters ------------------------ #

min_particles: 1000
max_particles: 2500
kld_err: 0.1
kld_z: 0.5

# --------------------- Update and Resampling Parameters --------------------- #

update_min_d: 0.03
update_min_a: 0.03
resample_interval: 1

# ------------------------------ Other settings ------------------------------ #

gui_publish_rate: 10.0
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0
transform_tolerance: 0.1
tf_broadcast: true
