# ---------------------------------------------------------------------------- #
#                          Cost map common parameters                          #
# ---------------------------------------------------------------------------- #

# Detail of the parameters can be found in the costmap_2d documentation
# https://docs.nav2.org/configuration/packages/configuring-costmaps.html

# Frame settings
footprint: [[0.32, 0.32], [0.32, -0.32],[-0.32, -0.32], [-0.32, 0.32]]
footprint_padding: 0.01

robot_base_frame: base_footprint

# Frequency
update_frequency: 1.5
publish_frequency: 1

# TF timeout
transform_tolerance: 5

# ------------------------------- Static Layer ------------------------------- #
# Loads a static map and incorporates it into the cost map.

static_layer:
  enabled: true
  map_topic: map
  subscribe_to_updates: true

# ------------------------------ Obstacle Layer ------------------------------ #
# Detects and incorporates dynamic obstacles into the cost map using sensor data

obstacle_layer:
  enabled: true
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: laser_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

  obstacle_range: 3.0 # 規劃時考慮幾公尺內的障礙物
  raytrace_range: 3.5 # 實時清除幾公尺內的障礙物

  max_obstacle_height: 0.5 # 障礙物最大高度
  min_obstacle_height: 0.0 # 障礙物最小高度

  unknown_threshold: 15 # 未知區域的閥值
  mark_threshold: 0 # 標記區域的閥值
  combination_method: 1 
  track_unknown_space: true # Set true to avoid global path planning through unknown space
  origin_z: 0.0 
  z_resolution: 0.2 
  z_voxels: 2 
  publish_voxel_map: false

# ------------------------------ Inflation Layer ----------------------------- #
# Expands obstacles in the cost map to account for the robot's size and safety buffer.

inflation_layer:
  enabled: true
  cost_scaling_factor: 4.0 # 增大比例因子會降低代價
  inflation_radius: 0.4


