# ---------------------------------------------------------------------------- #
#                         DWA local planner parameters                         #
# ---------------------------------------------------------------------------- #

base_global_planner: navfn/NavfnROS
base_local_planner: dwa_local_planner/DWAPlannerROS

controller_frequency: 5.0 # 發布速度指令的頻率
controller_patience: 15.0 # 在停止之前允許的最大時間

planner_frequency: 5.0
planner_patience: 15.0

oscillation_timeout: 10 # 在執行recovery前允許的最大振動時長
oscillation_distance: 0.3 # 允許來回振動的最小距離

recovery_behavior_enabled: true
shutdown_costmaps: false # 在不活動狀態時是否關閉costmap

DWAPlannerROS:

  # Robot Configuration Parameters
  max_vel_x: 1
  min_vel_x: -1

  max_vel_y: 1
  min_vel_y: -1

  # The velocity when robot is moving in a straight line
  max_vel_trans:  3
  min_vel_trans:  1

  max_vel_theta: 2.75
  min_vel_theta: 1.37

  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2 

  # Goal Tolerance Parametes
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.5
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 1.5
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40
  controller_frequency: 0.3

  # Trajectory Scoring Parameters
  path_distance_bias: 0.01
  goal_distance_bias: 0.01
  occdist_scale: 10
  forward_point_distance: 0.325
  stop_time_buffer: 0.4
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

  # Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
