# ---------------------------------------------------------------------------- #
#                           Global costmap parameters                          #
# ---------------------------------------------------------------------------- #

global_costmap:
  global_frame: map
  rolling_window: false
  track_unknown_space: true
  inflation_radius: 0.65

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
