local_costmap:
    global_frame: odom
    robot_base_frame: base_footprint
    update_frequency: 0.3
    publish_frequency: 0.3
    static_map: false
    rolling_window: true
    width: 3
    height: 3
    resolution: 0.05
    transform_tolerance: 0.5
    

    plugins:
        - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
        - {name: inflation_layer, type: "costmap_2d::InflationLayer"} 