# ---------------------------------------------------------------------------- #
#                           Local costmap parameters                           #
# ---------------------------------------------------------------------------- #

local_costmap:
  global_frame: map

  rolling_window: true
  width: 1.5
  height: 1.5
  resolution: 0.05
  origin_x: -0.75 
  origin_y: -0.75
  inflation_radius: 0.4

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
