twist_kalman_filter:
  Q:   [0.05, 0.05, 0.05, 0.01, 0.01, 0.01]  
  R:   [0.5,  0.5,  0.5,  0.2,  0.2,  0.2 ]  
  P0:  [1.0,  1.0,  1.0,  1.0,  1.0,  1.0 ]  
  x0:  [0.0,  0.0,  0.0,  0.0,  0.0,  0.0 ]  

"""
What will happen if larger these parameters

Q	: More trust in mesurement, faster response, but more noise.
R	: More trust in model, smoother, but may miss real changes.
P0: More trust in initial state, faster convergence, but may overshoot.
x0: The initial state estimate.

"""
